### ISSUE TITLE
Dokumentacija i kod

### ISSUE THREAD

**Issue by VojislavM** [Elektropioneer/Mali_Robot_2016#1]
@gproduct
- Dodajte par recenica generalnog opisa u [README.md](https://github.com/Elektropioneer/Mali_Robot_2016/blob/master/README.md). 
- U kodu nemojte da promenljive nazivate glupim, vec smislenim imenima (pocevsi od projekta)!

**Comment by silardg** [comment]
@VojislavM 
- [x] Dodacu README.md.  
  Ime za projekat je stavio Sava :sunglasses: , a za promenjive cemo da pazimo :+1:
